apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "external-secrets.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "external-secrets.labels" . | nindent 4 }}
  {{ with .Values.aws.iamRole }}
  annotations:
    iam.amazonaws.com/role: {{ . }}
  {{ end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "external-secrets.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "external-secrets.labels" . | nindent 8 }}
    spec:
      priorityClassName: system-cluster-critical
      serviceAccountName: {{ include "external-secrets.name" . }}
      containers:
        - name: external-secrets
          image: "ghcr.io/external-secrets/external-secrets:v{{ .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          args:
            - --enable-leader-election=true
            - --loglevel=info
            - --metrics-addr=:8080
          ports:
            - name: metrics
              containerPort: 8080
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
          securityContext:
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 65534
