apiVersion: v1
kind: Service
metadata:
  name: {{ include "external-secrets.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "external-secrets.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "external-secrets.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 8080
      name: metrics
      targetPort: metrics
