{{- if .Values.aws.enable }}
{{- $name := "aws-secrets-manager" }}
{{- if eq "aws" .Values.defaultProvider }}
{{- $name = "default" }}
{{- end }}
{{- with .Values.aws }}
apiVersion: external-secrets.io/v1alpha1
kind: ClusterSecretStore
metadata:
  name: {{ $name }}
  labels:
  {{- include "external-secrets.labels" $ | nindent 4 }}
spec:
  provider:
    aws:
      region: {{ .defaultRegion }}
      service: SecretsManager
      {{- if .eksRole }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "external-secrets.name" $ }}-{{ $name }}-store
            namespace: {{ $.Release.Namespace }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "external-secrets.name" $ }}-{{ $name }}-store
  namespace: {{ $.Release.Namespace }}
  labels:
  {{- include "external-secrets.labels" $ | nindent 4 }}
  {{- with .eksRole }}
  annotations:
    eks.amazonaws.com/role-arn: {{ . }}
  {{- end }}
  {{- end }}
{{- end }}
